// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DDSDataTypeObject.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _DDSDATA_TYPE_OBJECT_H_
#define _DDSDATA_TYPE_OBJECT_H_


#include <fastrtps/types/TypeObject.h>
#include <map>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DDSData_SOURCE)
#define DDSData_DllAPI __declspec( dllexport )
#else
#define DDSData_DllAPI __declspec( dllimport )
#endif // DDSData_SOURCE
#else
#define DDSData_DllAPI
#endif
#else
#define DDSData_DllAPI
#endif // _WIN32

using namespace eprosima::fastrtps::types;

eProsima_user_DllExport void registerDDSDataTypes();

eProsima_user_DllExport const TypeIdentifier* GetDataCollectionIntIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataCollectionIntObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataCollectionIntObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataCollectionIntObject();

eProsima_user_DllExport const TypeIdentifier* GetDataCollectionFloatIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataCollectionFloatObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataCollectionFloatObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataCollectionFloatObject();

eProsima_user_DllExport const TypeIdentifier* GetDataCollectionDoubleIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataCollectionDoubleObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataCollectionDoubleObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataCollectionDoubleObject();

eProsima_user_DllExport const TypeIdentifier* GetDataCharIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataCharObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataCharObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataCharObject();

eProsima_user_DllExport const TypeIdentifier* GetDataCollectionCharIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataCollectionCharObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataCollectionCharObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataCollectionCharObject();

eProsima_user_DllExport const TypeIdentifier* GetDDSDataIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDDSDataObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDDSDataObject();
eProsima_user_DllExport const TypeObject* GetCompleteDDSDataObject();


#endif // _DDSDATA_TYPE_OBJECT_H_