// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ConfigTopic.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_CONFIGTOPIC_H_
#define _FAST_DDS_GENERATED_CONFIGTOPIC_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ConfigTopic_SOURCE)
#define ConfigTopic_DllAPI __declspec( dllexport )
#else
#define ConfigTopic_DllAPI __declspec( dllimport )
#endif // ConfigTopic_SOURCE
#else
#define ConfigTopic_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ConfigTopic_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure ConfigTopic defined by the user in the IDL file.
 * @ingroup CONFIGTOPIC
 */
class ConfigTopic
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ConfigTopic();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ConfigTopic();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ConfigTopic that will be copied.
     */
    eProsima_user_DllExport ConfigTopic(
            const ConfigTopic& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ConfigTopic that will be copied.
     */
    eProsima_user_DllExport ConfigTopic(
            ConfigTopic&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ConfigTopic that will be copied.
     */
    eProsima_user_DllExport ConfigTopic& operator =(
            const ConfigTopic& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ConfigTopic that will be copied.
     */
    eProsima_user_DllExport ConfigTopic& operator =(
            ConfigTopic&& x);

    /*!
     * @brief Comparison operator.
     * @param x ConfigTopic object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ConfigTopic& x) const;

    /*!
     * @brief Comparison operator.
     * @param x ConfigTopic object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ConfigTopic& x) const;

    /*!
     * @brief This function sets a value in member subscriber_id
     * @param _subscriber_id New value for member subscriber_id
     */
    eProsima_user_DllExport void subscriber_id(
            int16_t _subscriber_id);

    /*!
     * @brief This function returns the value of member subscriber_id
     * @return Value of member subscriber_id
     */
    eProsima_user_DllExport int16_t subscriber_id() const;

    /*!
     * @brief This function returns a reference to member subscriber_id
     * @return Reference to member subscriber_id
     */
    eProsima_user_DllExport int16_t& subscriber_id();

    /*!
     * @brief This function sets a value in member vector_size
     * @param _vector_size New value for member vector_size
     */
    eProsima_user_DllExport void vector_size(
            uint16_t _vector_size);

    /*!
     * @brief This function returns the value of member vector_size
     * @return Value of member vector_size
     */
    eProsima_user_DllExport uint16_t vector_size() const;

    /*!
     * @brief This function returns a reference to member vector_size
     * @return Reference to member vector_size
     */
    eProsima_user_DllExport uint16_t& vector_size();

    /*!
     * @brief This function copies the value in member topictype_name
     * @param _topictype_name New value to be copied in member topictype_name
     */
    eProsima_user_DllExport void topictype_name(
            const std::string& _topictype_name);

    /*!
     * @brief This function moves the value in member topictype_name
     * @param _topictype_name New value to be moved in member topictype_name
     */
    eProsima_user_DllExport void topictype_name(
            std::string&& _topictype_name);

    /*!
     * @brief This function returns a constant reference to member topictype_name
     * @return Constant reference to member topictype_name
     */
    eProsima_user_DllExport const std::string& topictype_name() const;

    /*!
     * @brief This function returns a reference to member topictype_name
     * @return Reference to member topictype_name
     */
    eProsima_user_DllExport std::string& topictype_name();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const ConfigTopic& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    int16_t m_subscriber_id;
    uint16_t m_vector_size;
    std::string m_topictype_name;
};

#endif // _FAST_DDS_GENERATED_CONFIGTOPIC_H_