
/// <summary>
/// Topics control
/// </summary>

struct TopicCommand
{
	long long time_messege;
	unsigned long id_source;
	unsigned long id_target;
	unsigned long code_command;
	char parameter[256];
};

struct TopicStatus
{
	long long time_messege;
	unsigned long id_source;
	unsigned long id_target;
	unsigned long code_command;
	unsigned long code_status;
	char description[256];
};

/// <summary>
/// Topics data
/// </summary>
struct DataCollectionInt
{
	sequence<long> value;
	sequence<char> quality;
};

struct DataCollectionFloat
{
	sequence<float> value;
	sequence<char> quality;
};

struct DataCollectionDouble
{
	sequence<double> value;
	sequence<char> quality;
};

struct DataCollectionChar
{
	sequence<char> value;
	sequence<char> quality;
};

struct DataExInt
{
	long long time_source;
	unsigned long id_tag;
	long value;
	char quality;
};

struct DataExFloat
{
	long long time_source;
	unsigned long id_tag;
	float value;
	char quality;
};

struct DataExDouble
{
	long long time_source;
	unsigned long id_tag;
	double value;
	char quality;
};

struct DataExChar
{
	long long time_source;
	unsigned long id_tag;
	char value;
	char quality;
};

struct DDSData
{
	long long time_source;
	long long time_service;
	DataCollectionInt data_int;
	DataCollectionFloat data_float;
	DataCollectionDouble data_double;
	DataCollectionChar data_char;
};

struct DDSDataEx
{
	long long time_service;
	sequence<DataExInt> data_int;
	sequence<DataExFloat> data_float;
	sequence<DataExDouble> data_double;
	sequence<DataExChar> data_char;
};

/// <summary>
/// Tipocs alarm
/// </summary>

struct Alarm
{
	long long time_source;
	char value;
	char quality;
};

struct DDSAlarm
{
	long long time_source;
	long long time_service;
	sequence<unsigned long> alarms;
	sequence<unsigned long> quality;
};

struct DDSExAlarm
{
	long long time_service;
	sequence<Alarm> alarms;
};