// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TypeTopicsTypeObject.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _TYPETOPICS_TYPE_OBJECT_H_
#define _TYPETOPICS_TYPE_OBJECT_H_


#include <fastrtps/types/TypeObject.h>
#include <map>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TypeTopics_SOURCE)
#define TypeTopics_DllAPI __declspec( dllexport )
#else
#define TypeTopics_DllAPI __declspec( dllimport )
#endif // TypeTopics_SOURCE
#else
#define TypeTopics_DllAPI
#endif
#else
#define TypeTopics_DllAPI
#endif // _WIN32

using namespace eprosima::fastrtps::types;

eProsima_user_DllExport void registerTypeTopicsTypes();

eProsima_user_DllExport const TypeIdentifier* GetTopicCommandIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetTopicCommandObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalTopicCommandObject();
eProsima_user_DllExport const TypeObject* GetCompleteTopicCommandObject();

eProsima_user_DllExport const TypeIdentifier* GetTopicStatusIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetTopicStatusObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalTopicStatusObject();
eProsima_user_DllExport const TypeObject* GetCompleteTopicStatusObject();

eProsima_user_DllExport const TypeIdentifier* GetDataCollectionIntIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataCollectionIntObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataCollectionIntObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataCollectionIntObject();

eProsima_user_DllExport const TypeIdentifier* GetDataCollectionFloatIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataCollectionFloatObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataCollectionFloatObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataCollectionFloatObject();

eProsima_user_DllExport const TypeIdentifier* GetDataCollectionDoubleIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataCollectionDoubleObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataCollectionDoubleObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataCollectionDoubleObject();

eProsima_user_DllExport const TypeIdentifier* GetDataCollectionCharIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataCollectionCharObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataCollectionCharObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataCollectionCharObject();

eProsima_user_DllExport const TypeIdentifier* GetDataExIntIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataExIntObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataExIntObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataExIntObject();

eProsima_user_DllExport const TypeIdentifier* GetDataExFloatIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataExFloatObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataExFloatObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataExFloatObject();

eProsima_user_DllExport const TypeIdentifier* GetDataExDoubleIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataExDoubleObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataExDoubleObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataExDoubleObject();

eProsima_user_DllExport const TypeIdentifier* GetDataExCharIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataExCharObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataExCharObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataExCharObject();

eProsima_user_DllExport const TypeIdentifier* GetDDSDataIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDDSDataObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDDSDataObject();
eProsima_user_DllExport const TypeObject* GetCompleteDDSDataObject();

eProsima_user_DllExport const TypeIdentifier* GetDDSDataExIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDDSDataExObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDDSDataExObject();
eProsima_user_DllExport const TypeObject* GetCompleteDDSDataExObject();

eProsima_user_DllExport const TypeIdentifier* GetAlarmIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetAlarmObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalAlarmObject();
eProsima_user_DllExport const TypeObject* GetCompleteAlarmObject();

eProsima_user_DllExport const TypeIdentifier* GetDDSAlarmIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDDSAlarmObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDDSAlarmObject();
eProsima_user_DllExport const TypeObject* GetCompleteDDSAlarmObject();

eProsima_user_DllExport const TypeIdentifier* GetDDSExAlarmIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDDSExAlarmObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDDSExAlarmObject();
eProsima_user_DllExport const TypeObject* GetCompleteDDSExAlarmObject();


#endif // _TYPETOPICS_TYPE_OBJECT_H_