// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DDSDataExTypeObject.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _DDSDATAEX_TYPE_OBJECT_H_
#define _DDSDATAEX_TYPE_OBJECT_H_


#include <fastrtps/types/TypeObject.h>
#include <map>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DDSDataEx_SOURCE)
#define DDSDataEx_DllAPI __declspec( dllexport )
#else
#define DDSDataEx_DllAPI __declspec( dllimport )
#endif // DDSDataEx_SOURCE
#else
#define DDSDataEx_DllAPI
#endif
#else
#define DDSDataEx_DllAPI
#endif // _WIN32

using namespace eprosima::fastrtps::types;

eProsima_user_DllExport void registerDDSDataExTypes();

eProsima_user_DllExport const TypeIdentifier* GetDataExIntIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataExIntObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataExIntObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataExIntObject();

eProsima_user_DllExport const TypeIdentifier* GetDataExFloatIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataExFloatObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataExFloatObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataExFloatObject();

eProsima_user_DllExport const TypeIdentifier* GetDataExDoubleIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataExDoubleObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataExDoubleObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataExDoubleObject();

eProsima_user_DllExport const TypeIdentifier* GetDataExCharIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDataExCharObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDataExCharObject();
eProsima_user_DllExport const TypeObject* GetCompleteDataExCharObject();

eProsima_user_DllExport const TypeIdentifier* GetDDSDataExIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetDDSDataExObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalDDSDataExObject();
eProsima_user_DllExport const TypeObject* GetCompleteDDSDataExObject();


#endif // _DDSDATAEX_TYPE_OBJECT_H_