// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DDSDataExTypeObject.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "DDSDataEx.h"
#include "DDSDataExTypeObject.h"
#include <utility>
#include <sstream>
#include <fastrtps/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>
#include <fastrtps/types/TypeObjectFactory.h>
#include <fastrtps/types/TypeNamesGenerator.h>
#include <fastrtps/types/AnnotationParameterValue.h>
#include <fastcdr/FastBuffer.h>
#include <fastcdr/Cdr.h>

using namespace eprosima::fastrtps::rtps;

void registerDDSDataExTypes()
{
    TypeObjectFactory *factory = TypeObjectFactory::get_instance();
    factory->add_type_object("DataExInt", GetDataExIntIdentifier(true), GetDataExIntObject(true));
    factory->add_type_object("DataExInt", GetDataExIntIdentifier(false), GetDataExIntObject(false));

    factory->add_type_object("DataExFloat", GetDataExFloatIdentifier(true), GetDataExFloatObject(true));
    factory->add_type_object("DataExFloat", GetDataExFloatIdentifier(false), GetDataExFloatObject(false));

    factory->add_type_object("DataExDouble", GetDataExDoubleIdentifier(true), GetDataExDoubleObject(true));
    factory->add_type_object("DataExDouble", GetDataExDoubleIdentifier(false), GetDataExDoubleObject(false));

    factory->add_type_object("DataExChar", GetDataExCharIdentifier(true), GetDataExCharObject(true));
    factory->add_type_object("DataExChar", GetDataExCharIdentifier(false), GetDataExCharObject(false));

    factory->add_type_object("DDSDataEx", GetDDSDataExIdentifier(true), GetDDSDataExObject(true));
    factory->add_type_object("DDSDataEx", GetDDSDataExIdentifier(false), GetDDSDataExObject(false));

}

const TypeIdentifier* GetDataExIntIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("DataExInt", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetDataExIntObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("DataExInt", complete);
}

const TypeObject* GetDataExIntObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExInt", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteDataExIntObject();
    }
    //else
    return GetMinimalDataExIntObject();
}

const TypeObject* GetMinimalDataExIntObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExInt", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_time_source;
    mst_time_source.common().member_id(memberId++);
    mst_time_source.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_time_source.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_time_source.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_time_source.common().member_flags().IS_OPTIONAL(false);
    mst_time_source.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_time_source.common().member_flags().IS_KEY(false);
    mst_time_source.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int64_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_time_source.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 time_source_hash("time_source");
    for(int i = 0; i < 4; ++i)
    {
        mst_time_source.detail().name_hash()[i] = time_source_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_time_source);

    MinimalStructMember mst_id_tag;
    mst_id_tag.common().member_id(memberId++);
    mst_id_tag.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_id_tag.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_id_tag.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_id_tag.common().member_flags().IS_OPTIONAL(false);
    mst_id_tag.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_id_tag.common().member_flags().IS_KEY(false);
    mst_id_tag.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "uint32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_id_tag.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 id_tag_hash("id_tag");
    for(int i = 0; i < 4; ++i)
    {
        mst_id_tag.detail().name_hash()[i] = id_tag_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_id_tag);

    MinimalStructMember mst_value;
    mst_value.common().member_id(memberId++);
    mst_value.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_value.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_value.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_value.common().member_flags().IS_OPTIONAL(false);
    mst_value.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_value.common().member_flags().IS_KEY(false);
    mst_value.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_value.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 value_hash("value");
    for(int i = 0; i < 4; ++i)
    {
        mst_value.detail().name_hash()[i] = value_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_value);

    MinimalStructMember mst_quality;
    mst_quality.common().member_id(memberId++);
    mst_quality.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_quality.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_quality.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_quality.common().member_flags().IS_OPTIONAL(false);
    mst_quality.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_quality.common().member_flags().IS_KEY(false);
    mst_quality.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "char";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_quality.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 quality_hash("quality");
    for(int i = 0; i < 4; ++i)
    {
        mst_quality.detail().name_hash()[i] = quality_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_quality);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DataExInt", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DataExInt", false);
}

const TypeObject* GetCompleteDataExIntObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExInt", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_time_source;
    cst_time_source.common().member_id(memberId++);
    cst_time_source.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_time_source.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_time_source.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_time_source.common().member_flags().IS_OPTIONAL(false);
    cst_time_source.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_time_source.common().member_flags().IS_KEY(false);
    cst_time_source.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int64_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_time_source.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_time_source.detail().name("time_source");

    type_object->complete().struct_type().member_seq().emplace_back(cst_time_source);

    CompleteStructMember cst_id_tag;
    cst_id_tag.common().member_id(memberId++);
    cst_id_tag.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_id_tag.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_id_tag.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_id_tag.common().member_flags().IS_OPTIONAL(false);
    cst_id_tag.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_id_tag.common().member_flags().IS_KEY(false);
    cst_id_tag.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "uint32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_id_tag.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_id_tag.detail().name("id_tag");

    type_object->complete().struct_type().member_seq().emplace_back(cst_id_tag);

    CompleteStructMember cst_value;
    cst_value.common().member_id(memberId++);
    cst_value.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_value.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_value.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_value.common().member_flags().IS_OPTIONAL(false);
    cst_value.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_value.common().member_flags().IS_KEY(false);
    cst_value.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_value.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_value.detail().name("value");

    type_object->complete().struct_type().member_seq().emplace_back(cst_value);

    CompleteStructMember cst_quality;
    cst_quality.common().member_id(memberId++);
    cst_quality.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_quality.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_quality.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_quality.common().member_flags().IS_OPTIONAL(false);
    cst_quality.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_quality.common().member_flags().IS_KEY(false);
    cst_quality.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "char";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_quality.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_quality.detail().name("quality");

    type_object->complete().struct_type().member_seq().emplace_back(cst_quality);


    // Header
    type_object->complete().struct_type().header().detail().type_name("DataExInt");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DataExInt", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DataExInt", true);
}

const TypeIdentifier* GetDataExFloatIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("DataExFloat", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetDataExFloatObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("DataExFloat", complete);
}

const TypeObject* GetDataExFloatObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExFloat", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteDataExFloatObject();
    }
    //else
    return GetMinimalDataExFloatObject();
}

const TypeObject* GetMinimalDataExFloatObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExFloat", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_time_source;
    mst_time_source.common().member_id(memberId++);
    mst_time_source.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_time_source.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_time_source.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_time_source.common().member_flags().IS_OPTIONAL(false);
    mst_time_source.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_time_source.common().member_flags().IS_KEY(false);
    mst_time_source.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int64_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_time_source.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 time_source_hash("time_source");
    for(int i = 0; i < 4; ++i)
    {
        mst_time_source.detail().name_hash()[i] = time_source_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_time_source);

    MinimalStructMember mst_id_tag;
    mst_id_tag.common().member_id(memberId++);
    mst_id_tag.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_id_tag.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_id_tag.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_id_tag.common().member_flags().IS_OPTIONAL(false);
    mst_id_tag.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_id_tag.common().member_flags().IS_KEY(false);
    mst_id_tag.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "uint32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_id_tag.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 id_tag_hash("id_tag");
    for(int i = 0; i < 4; ++i)
    {
        mst_id_tag.detail().name_hash()[i] = id_tag_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_id_tag);

    MinimalStructMember mst_value;
    mst_value.common().member_id(memberId++);
    mst_value.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_value.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_value.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_value.common().member_flags().IS_OPTIONAL(false);
    mst_value.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_value.common().member_flags().IS_KEY(false);
    mst_value.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "float";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_value.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 value_hash("value");
    for(int i = 0; i < 4; ++i)
    {
        mst_value.detail().name_hash()[i] = value_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_value);

    MinimalStructMember mst_quality;
    mst_quality.common().member_id(memberId++);
    mst_quality.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_quality.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_quality.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_quality.common().member_flags().IS_OPTIONAL(false);
    mst_quality.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_quality.common().member_flags().IS_KEY(false);
    mst_quality.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "char";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_quality.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 quality_hash("quality");
    for(int i = 0; i < 4; ++i)
    {
        mst_quality.detail().name_hash()[i] = quality_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_quality);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DataExFloat", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DataExFloat", false);
}

const TypeObject* GetCompleteDataExFloatObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExFloat", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_time_source;
    cst_time_source.common().member_id(memberId++);
    cst_time_source.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_time_source.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_time_source.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_time_source.common().member_flags().IS_OPTIONAL(false);
    cst_time_source.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_time_source.common().member_flags().IS_KEY(false);
    cst_time_source.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int64_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_time_source.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_time_source.detail().name("time_source");

    type_object->complete().struct_type().member_seq().emplace_back(cst_time_source);

    CompleteStructMember cst_id_tag;
    cst_id_tag.common().member_id(memberId++);
    cst_id_tag.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_id_tag.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_id_tag.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_id_tag.common().member_flags().IS_OPTIONAL(false);
    cst_id_tag.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_id_tag.common().member_flags().IS_KEY(false);
    cst_id_tag.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "uint32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_id_tag.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_id_tag.detail().name("id_tag");

    type_object->complete().struct_type().member_seq().emplace_back(cst_id_tag);

    CompleteStructMember cst_value;
    cst_value.common().member_id(memberId++);
    cst_value.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_value.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_value.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_value.common().member_flags().IS_OPTIONAL(false);
    cst_value.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_value.common().member_flags().IS_KEY(false);
    cst_value.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "float";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_value.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_value.detail().name("value");

    type_object->complete().struct_type().member_seq().emplace_back(cst_value);

    CompleteStructMember cst_quality;
    cst_quality.common().member_id(memberId++);
    cst_quality.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_quality.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_quality.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_quality.common().member_flags().IS_OPTIONAL(false);
    cst_quality.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_quality.common().member_flags().IS_KEY(false);
    cst_quality.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "char";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_quality.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_quality.detail().name("quality");

    type_object->complete().struct_type().member_seq().emplace_back(cst_quality);


    // Header
    type_object->complete().struct_type().header().detail().type_name("DataExFloat");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DataExFloat", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DataExFloat", true);
}

const TypeIdentifier* GetDataExDoubleIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("DataExDouble", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetDataExDoubleObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("DataExDouble", complete);
}

const TypeObject* GetDataExDoubleObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExDouble", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteDataExDoubleObject();
    }
    //else
    return GetMinimalDataExDoubleObject();
}

const TypeObject* GetMinimalDataExDoubleObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExDouble", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_time_source;
    mst_time_source.common().member_id(memberId++);
    mst_time_source.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_time_source.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_time_source.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_time_source.common().member_flags().IS_OPTIONAL(false);
    mst_time_source.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_time_source.common().member_flags().IS_KEY(false);
    mst_time_source.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int64_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_time_source.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 time_source_hash("time_source");
    for(int i = 0; i < 4; ++i)
    {
        mst_time_source.detail().name_hash()[i] = time_source_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_time_source);

    MinimalStructMember mst_id_tag;
    mst_id_tag.common().member_id(memberId++);
    mst_id_tag.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_id_tag.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_id_tag.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_id_tag.common().member_flags().IS_OPTIONAL(false);
    mst_id_tag.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_id_tag.common().member_flags().IS_KEY(false);
    mst_id_tag.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "uint32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_id_tag.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 id_tag_hash("id_tag");
    for(int i = 0; i < 4; ++i)
    {
        mst_id_tag.detail().name_hash()[i] = id_tag_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_id_tag);

    MinimalStructMember mst_value;
    mst_value.common().member_id(memberId++);
    mst_value.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_value.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_value.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_value.common().member_flags().IS_OPTIONAL(false);
    mst_value.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_value.common().member_flags().IS_KEY(false);
    mst_value.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "double";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_value.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 value_hash("value");
    for(int i = 0; i < 4; ++i)
    {
        mst_value.detail().name_hash()[i] = value_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_value);

    MinimalStructMember mst_quality;
    mst_quality.common().member_id(memberId++);
    mst_quality.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_quality.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_quality.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_quality.common().member_flags().IS_OPTIONAL(false);
    mst_quality.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_quality.common().member_flags().IS_KEY(false);
    mst_quality.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "char";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_quality.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 quality_hash("quality");
    for(int i = 0; i < 4; ++i)
    {
        mst_quality.detail().name_hash()[i] = quality_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_quality);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DataExDouble", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DataExDouble", false);
}

const TypeObject* GetCompleteDataExDoubleObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExDouble", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_time_source;
    cst_time_source.common().member_id(memberId++);
    cst_time_source.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_time_source.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_time_source.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_time_source.common().member_flags().IS_OPTIONAL(false);
    cst_time_source.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_time_source.common().member_flags().IS_KEY(false);
    cst_time_source.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int64_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_time_source.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_time_source.detail().name("time_source");

    type_object->complete().struct_type().member_seq().emplace_back(cst_time_source);

    CompleteStructMember cst_id_tag;
    cst_id_tag.common().member_id(memberId++);
    cst_id_tag.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_id_tag.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_id_tag.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_id_tag.common().member_flags().IS_OPTIONAL(false);
    cst_id_tag.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_id_tag.common().member_flags().IS_KEY(false);
    cst_id_tag.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "uint32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_id_tag.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_id_tag.detail().name("id_tag");

    type_object->complete().struct_type().member_seq().emplace_back(cst_id_tag);

    CompleteStructMember cst_value;
    cst_value.common().member_id(memberId++);
    cst_value.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_value.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_value.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_value.common().member_flags().IS_OPTIONAL(false);
    cst_value.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_value.common().member_flags().IS_KEY(false);
    cst_value.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "double";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_value.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_value.detail().name("value");

    type_object->complete().struct_type().member_seq().emplace_back(cst_value);

    CompleteStructMember cst_quality;
    cst_quality.common().member_id(memberId++);
    cst_quality.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_quality.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_quality.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_quality.common().member_flags().IS_OPTIONAL(false);
    cst_quality.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_quality.common().member_flags().IS_KEY(false);
    cst_quality.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "char";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_quality.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_quality.detail().name("quality");

    type_object->complete().struct_type().member_seq().emplace_back(cst_quality);


    // Header
    type_object->complete().struct_type().header().detail().type_name("DataExDouble");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DataExDouble", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DataExDouble", true);
}

const TypeIdentifier* GetDataExCharIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("DataExChar", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetDataExCharObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("DataExChar", complete);
}

const TypeObject* GetDataExCharObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExChar", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteDataExCharObject();
    }
    //else
    return GetMinimalDataExCharObject();
}

const TypeObject* GetMinimalDataExCharObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExChar", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_time_source;
    mst_time_source.common().member_id(memberId++);
    mst_time_source.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_time_source.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_time_source.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_time_source.common().member_flags().IS_OPTIONAL(false);
    mst_time_source.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_time_source.common().member_flags().IS_KEY(false);
    mst_time_source.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int64_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_time_source.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 time_source_hash("time_source");
    for(int i = 0; i < 4; ++i)
    {
        mst_time_source.detail().name_hash()[i] = time_source_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_time_source);

    MinimalStructMember mst_id_tag;
    mst_id_tag.common().member_id(memberId++);
    mst_id_tag.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_id_tag.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_id_tag.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_id_tag.common().member_flags().IS_OPTIONAL(false);
    mst_id_tag.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_id_tag.common().member_flags().IS_KEY(false);
    mst_id_tag.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "uint32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_id_tag.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 id_tag_hash("id_tag");
    for(int i = 0; i < 4; ++i)
    {
        mst_id_tag.detail().name_hash()[i] = id_tag_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_id_tag);

    MinimalStructMember mst_value;
    mst_value.common().member_id(memberId++);
    mst_value.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_value.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_value.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_value.common().member_flags().IS_OPTIONAL(false);
    mst_value.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_value.common().member_flags().IS_KEY(false);
    mst_value.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_value.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("char", 0, false));


    MD5 value_hash("value");
    for(int i = 0; i < 4; ++i)
    {
        mst_value.detail().name_hash()[i] = value_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_value);

    MinimalStructMember mst_quality;
    mst_quality.common().member_id(memberId++);
    mst_quality.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_quality.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_quality.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_quality.common().member_flags().IS_OPTIONAL(false);
    mst_quality.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_quality.common().member_flags().IS_KEY(false);
    mst_quality.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "char";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_quality.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 quality_hash("quality");
    for(int i = 0; i < 4; ++i)
    {
        mst_quality.detail().name_hash()[i] = quality_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_quality);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DataExChar", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DataExChar", false);
}

const TypeObject* GetCompleteDataExCharObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataExChar", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_time_source;
    cst_time_source.common().member_id(memberId++);
    cst_time_source.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_time_source.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_time_source.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_time_source.common().member_flags().IS_OPTIONAL(false);
    cst_time_source.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_time_source.common().member_flags().IS_KEY(false);
    cst_time_source.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int64_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_time_source.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_time_source.detail().name("time_source");

    type_object->complete().struct_type().member_seq().emplace_back(cst_time_source);

    CompleteStructMember cst_id_tag;
    cst_id_tag.common().member_id(memberId++);
    cst_id_tag.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_id_tag.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_id_tag.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_id_tag.common().member_flags().IS_OPTIONAL(false);
    cst_id_tag.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_id_tag.common().member_flags().IS_KEY(false);
    cst_id_tag.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "uint32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_id_tag.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_id_tag.detail().name("id_tag");

    type_object->complete().struct_type().member_seq().emplace_back(cst_id_tag);

    CompleteStructMember cst_value;
    cst_value.common().member_id(memberId++);
    cst_value.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_value.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_value.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_value.common().member_flags().IS_OPTIONAL(false);
    cst_value.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_value.common().member_flags().IS_KEY(false);
    cst_value.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_value.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("char", 0, true));


    cst_value.detail().name("value");

    type_object->complete().struct_type().member_seq().emplace_back(cst_value);

    CompleteStructMember cst_quality;
    cst_quality.common().member_id(memberId++);
    cst_quality.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_quality.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_quality.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_quality.common().member_flags().IS_OPTIONAL(false);
    cst_quality.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_quality.common().member_flags().IS_KEY(false);
    cst_quality.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "char";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_quality.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_quality.detail().name("quality");

    type_object->complete().struct_type().member_seq().emplace_back(cst_quality);


    // Header
    type_object->complete().struct_type().header().detail().type_name("DataExChar");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DataExChar", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DataExChar", true);
}

const TypeIdentifier* GetDDSDataExIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("DDSDataEx", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetDDSDataExObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("DDSDataEx", complete);
}

const TypeObject* GetDDSDataExObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DDSDataEx", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteDDSDataExObject();
    }
    //else
    return GetMinimalDDSDataExObject();
}

const TypeObject* GetMinimalDDSDataExObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DDSDataEx", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_time_service;
    mst_time_service.common().member_id(memberId++);
    mst_time_service.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_time_service.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_time_service.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_time_service.common().member_flags().IS_OPTIONAL(false);
    mst_time_service.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_time_service.common().member_flags().IS_KEY(false);
    mst_time_service.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int64_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_time_service.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 time_service_hash("time_service");
    for(int i = 0; i < 4; ++i)
    {
        mst_time_service.detail().name_hash()[i] = time_service_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_time_service);

    MinimalStructMember mst_data_int;
    mst_data_int.common().member_id(memberId++);
    mst_data_int.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_data_int.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_data_int.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_data_int.common().member_flags().IS_OPTIONAL(false);
    mst_data_int.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_data_int.common().member_flags().IS_KEY(false);
    mst_data_int.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_data_int.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("DataExInt", 0, false));


    MD5 data_int_hash("data_int");
    for(int i = 0; i < 4; ++i)
    {
        mst_data_int.detail().name_hash()[i] = data_int_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_data_int);

    MinimalStructMember mst_data_float;
    mst_data_float.common().member_id(memberId++);
    mst_data_float.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_data_float.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_data_float.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_data_float.common().member_flags().IS_OPTIONAL(false);
    mst_data_float.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_data_float.common().member_flags().IS_KEY(false);
    mst_data_float.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_data_float.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("DataExFloat", 0, false));


    MD5 data_float_hash("data_float");
    for(int i = 0; i < 4; ++i)
    {
        mst_data_float.detail().name_hash()[i] = data_float_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_data_float);

    MinimalStructMember mst_data_double;
    mst_data_double.common().member_id(memberId++);
    mst_data_double.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_data_double.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_data_double.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_data_double.common().member_flags().IS_OPTIONAL(false);
    mst_data_double.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_data_double.common().member_flags().IS_KEY(false);
    mst_data_double.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_data_double.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("DataExDouble", 0, false));


    MD5 data_double_hash("data_double");
    for(int i = 0; i < 4; ++i)
    {
        mst_data_double.detail().name_hash()[i] = data_double_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_data_double);

    MinimalStructMember mst_data_char;
    mst_data_char.common().member_id(memberId++);
    mst_data_char.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_data_char.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_data_char.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_data_char.common().member_flags().IS_OPTIONAL(false);
    mst_data_char.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_data_char.common().member_flags().IS_KEY(false);
    mst_data_char.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_data_char.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("DataExChar", 0, false));


    MD5 data_char_hash("data_char");
    for(int i = 0; i < 4; ++i)
    {
        mst_data_char.detail().name_hash()[i] = data_char_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_data_char);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DDSDataEx", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DDSDataEx", false);
}

const TypeObject* GetCompleteDDSDataExObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DDSDataEx", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_time_service;
    cst_time_service.common().member_id(memberId++);
    cst_time_service.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_time_service.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_time_service.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_time_service.common().member_flags().IS_OPTIONAL(false);
    cst_time_service.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_time_service.common().member_flags().IS_KEY(false);
    cst_time_service.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int64_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_time_service.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_time_service.detail().name("time_service");

    type_object->complete().struct_type().member_seq().emplace_back(cst_time_service);

    CompleteStructMember cst_data_int;
    cst_data_int.common().member_id(memberId++);
    cst_data_int.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_data_int.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_data_int.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_data_int.common().member_flags().IS_OPTIONAL(false);
    cst_data_int.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_data_int.common().member_flags().IS_KEY(false);
    cst_data_int.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_data_int.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("DataExInt", 0, true));


    cst_data_int.detail().name("data_int");

    type_object->complete().struct_type().member_seq().emplace_back(cst_data_int);

    CompleteStructMember cst_data_float;
    cst_data_float.common().member_id(memberId++);
    cst_data_float.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_data_float.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_data_float.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_data_float.common().member_flags().IS_OPTIONAL(false);
    cst_data_float.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_data_float.common().member_flags().IS_KEY(false);
    cst_data_float.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_data_float.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("DataExFloat", 0, true));


    cst_data_float.detail().name("data_float");

    type_object->complete().struct_type().member_seq().emplace_back(cst_data_float);

    CompleteStructMember cst_data_double;
    cst_data_double.common().member_id(memberId++);
    cst_data_double.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_data_double.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_data_double.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_data_double.common().member_flags().IS_OPTIONAL(false);
    cst_data_double.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_data_double.common().member_flags().IS_KEY(false);
    cst_data_double.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_data_double.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("DataExDouble", 0, true));


    cst_data_double.detail().name("data_double");

    type_object->complete().struct_type().member_seq().emplace_back(cst_data_double);

    CompleteStructMember cst_data_char;
    cst_data_char.common().member_id(memberId++);
    cst_data_char.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_data_char.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_data_char.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_data_char.common().member_flags().IS_OPTIONAL(false);
    cst_data_char.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_data_char.common().member_flags().IS_KEY(false);
    cst_data_char.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_data_char.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("DataExChar", 0, true));


    cst_data_char.detail().name("data_char");

    type_object->complete().struct_type().member_seq().emplace_back(cst_data_char);


    // Header
    type_object->complete().struct_type().header().detail().type_name("DDSDataEx");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DDSDataEx", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DDSDataEx", true);
}
